version: "3.9"

services:
  wt2-system-prompt-disclosure:
    build: .

    container_name: wt2-system-prompt-disclosure

    ports:
      - "8501:8501"

    env_file:
      - .env.example

    restart: unless-stopped